import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { Parser } from 'n3';
import { checkCatalog, CATALOG_PATH } from '../offline/graph-catalog';

const HEAD = `@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix void: <http://rdfs.org/ns/void#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix role: <urn:reckons:graph-role/> .
@prefix graph: <urn:reckons:graph/> .
role:design skos:inScheme role:scheme ; skos:prefLabel "Design" .
role:observed skos:inScheme role:scheme ; skos:prefLabel "Observed" .
`;
const parse = (ttl: string) => new Parser().parse(HEAD + ttl);
const exists = (paths: string[]) => (p: string) => paths.includes(p);

describe('checkCatalog', () => {
  it('passes when every graph is declared once with one role', () => {
    const quads = parse(`graph:a a void:Dataset ; dcterms:source "static/a.ttl" ; dcterms:type role:design .`);
    expect(checkCatalog(quads, ['a.ttl'], exists(['static/a.ttl']))).toEqual([]);
  });

  it('fails on a graph added without a catalog entry', () => {
    const quads = parse(`graph:a a void:Dataset ; dcterms:source "static/a.ttl" ; dcterms:type role:design .`);
    expect(checkCatalog(quads, ['a.ttl', 'b.ttl'], exists(['static/a.ttl', 'static/b.ttl']))).toEqual([
      expect.stringContaining('static/b.ttl is not in the catalog'),
    ]);
  });

  it('fails on an entry whose file is gone, a missing role, and a role outside the scheme', () => {
    const quads = parse(`
      graph:gone a void:Dataset ; dcterms:source "static/gone.ttl" ; dcterms:type role:design .
      graph:none a void:Dataset ; dcterms:source "static/none.ttl" .
      graph:odd a void:Dataset ; dcterms:source "static/odd.ttl" ; dcterms:type role:vibes .`);
    const problems = checkCatalog(quads, ['none.ttl', 'odd.ttl'], exists(['static/none.ttl', 'static/odd.ttl']));
    expect(problems).toEqual(expect.arrayContaining([
      expect.stringContaining('static/gone.ttl, which does not exist'),
      expect.stringContaining('graph/none has 0 roles'),
      expect.stringContaining('role:vibes'.replace('role:', 'urn:reckons:graph-role/')),
    ]));
  });

  it('fails when a named generator script no longer exists, or a pairing points nowhere', () => {
    const quads = parse(`graph:o a void:Dataset ; dcterms:source "static/o.ttl" ; dcterms:type role:observed ;
      prov:wasGeneratedBy <urn:reckons:script/scripts/gone.ts> ; prov:wasInfluencedBy graph:missing .`);
    const problems = checkCatalog(quads, ['o.ttl'], exists(['static/o.ttl']));
    expect(problems).toEqual(expect.arrayContaining([
      expect.stringContaining('generated by scripts/gone.ts, which does not exist'),
      expect.stringContaining('influenced by urn:reckons:graph/missing'),
    ]));
  });

  it('holds for the real catalog', () => {
    const quads = new Parser().parse(readFileSync(CATALOG_PATH, 'utf8'));
    const files = readdirSync('static').filter((f) => f.endsWith('.ttl'));
    expect(checkCatalog(quads, files, existsSync)).toEqual([]);
  });
});
