/**
 * Triage — the one place that decides what a pending item IS (F80, SCRIPT tier).
 *
 * The pending queue is a junk drawer: blocking decisions, actionable findings, and re-derivable
 * noise all land in the same file. Left undifferentiated it grows without bound — 83 "questions"
 * of which zero were actually a decision Matt had to make (2026-07-16). This module is the shared
 * classifier that sorts them into THREE channels, so each item goes to the right place instead of
 * all of them piling onto the human:
 *
 *   rederivable  — a check regenerates this every run. NEVER a queue item; fix the source or accept.
 *   remediable   — a known job clears the whole cluster. Becomes an agent TASK (tasks.ttl).
 *   judgment     — genuinely needs a human/Opus. The REAL backlog.
 *
 * And within judgment, one finer cut the desk depends on:
 *   a DESK QUESTION is a judgment item of type 'question' — a decision that, once answered,
 *   unblocks an agent. Everything else judgment (a test to write, a constraint to know) is
 *   backlog WORK, not a yes/no for Matt. Both `orchestrate` and the question `desk` import this
 *   so they can never disagree about what belongs where.
 */

export interface PendingItem {
  subject: string;
  predicate: string;
  question?: string;
  object?: unknown;
  type?: string;
  agent?: string;
  priority?: 'low' | 'medium' | 'high' | string;
  blocks?: string;
  addedAt?: string;
  note?: string;
}

export type TriageKind = 'rederivable' | 'remediable' | 'judgment';

export interface Remedy {
  kind: TriageKind;
  note: string;
  command?: string;
  doneWhen?: string;
  tier?: 'script' | 'local-agent';
}

/**
 * How to clear a whole cluster, by signature: a lookup from "what keeps showing up" to "the one
 * action that settles all of it". Unknown signatures fail toward the human (judgment), per F88.
 */
export const REMEDIES: Record<string, Remedy> = {
  'graph-lint/predicate-economy': { kind: 'rederivable', note: 'graph-lint regenerates this every run — it is a design nudge, not a queue item. Address by naming real relations in the TTL, or accept it.' },
  'graph-lint/dangling-ref': { kind: 'rederivable', note: 'regenerated by graph-lint. Fix the TTL reference; do not triage.' },
  'graph-lint/dead-link': { kind: 'rederivable', note: 'regenerated by graph-lint. Fix or remove the has-file/tested-by path.' },
  'graph-lint/duplicate-id': { kind: 'rederivable', note: 'regenerated by graph-lint. Renumber the colliding feature-id.' },
  'graph-lint/incomplete': { kind: 'remediable', note: 'entities missing a description — the local model can draft them.', command: 'npx tsx scripts/offline/describe-entities.ts', doneWhen: 'npx tsx scripts/offline/graph-lint.ts', tier: 'local-agent' },
  'sweep/parse-error': { kind: 'remediable', note: 'a workspace .ttl does not parse — a script can flag exactly which line; a human fixes it.', command: 'npx tsx scripts/offline/graph-lint.ts', doneWhen: 'npx tsx scripts/offline/graph-lint.ts', tier: 'script' },
  'history-lessons/fix-without-test': { kind: 'judgment', note: 'each is a past fix with no test. Real, but it is a BACKLOG to write tests, not a click — and which to write is judgment.' },
  'history-lessons/fragility-hotspot': { kind: 'judgment', note: 'files that keep needing fixes. A design question, not a triage item.' },
  'competitor-scan/copyleft': { kind: 'judgment', note: 'a competitor is copyleft against our MIT. A standing constraint to KNOW, not a task.' },
  'competitor-scan/candidate': { kind: 'judgment', note: 'a candidate competitor to confirm or dismiss. Light judgment; blocks nothing.' },
  'local review': { kind: 'judgment', note: 'a local-model code-review finding. A PROPOSAL to verify then fix or dismiss — some are false positives — not a blocking decision.' },
};

/** The signature of a finding: `[agent/check]` prefix if present, else agent + type. */
export function signature(p: PendingItem): string {
  const m = (p.question ?? '').match(/^\[([\w /-]+?)\]/);
  if (m) {
    const tag = m[1].trim();
    return tag.includes('/') ? tag.split('/').slice(0, 2).join('/') : tag;
  }
  return `${(p.agent ?? '?').replace(/^offline:/, '')}/${p.type ?? 'note'}`;
}

export function remedyFor(sig: string): Remedy {
  return REMEDIES[sig] ?? { kind: 'judgment', note: 'no known remediation — route to a human.' };
}

export function classify(p: PendingItem): Remedy {
  return remedyFor(signature(p));
}

/**
 * A DESK QUESTION: a judgment item of type 'question' — a decision that, answered, unblocks an
 * agent. Observations, drift-warnings, suggestions, re-derivable stats and remediable clusters
 * are NOT desk questions, no matter how much explanatory text they carry.
 */
export function isDeskQuestion(p: PendingItem): boolean {
  return p.type === 'question' && p.object == null && classify(p).kind === 'judgment';
}

/** How many whole days a pending item has waited — the "carried over" dimension. */
export function ageDays(p: PendingItem, now = Date.now()): number {
  if (!p.addedAt) return 0;
  const t = Date.parse(p.addedAt);
  if (Number.isNaN(t)) return 0;
  return Math.max(0, Math.floor((now - t) / 86_400_000));
}

/** Is this item holding up named work? The "blocking" dimension. */
export function isBlocking(p: PendingItem): boolean {
  return typeof p.blocks === 'string' && p.blocks.length > 0;
}
