#!/usr/bin/env npx tsx
/**
 * THE OFFLINE JOBS, AS TRIPLES AND SETS — so the graph UI that already exists can show them.
 *
 * Matt, 2026-09-09: "Our jobs could be defined in triples and sets I assume? We maybe just need to
 * add a bit to the main Graph UI and that should cover it."
 *
 * That is the whole design, and it dissolves the problem rather than solving it. Reckons already
 * renders a graph — 2D canvas and 3D WebGL, entities drawn by type with their own geometry and
 * icon. A job that is an ENTITY is already a node, so the interface for managing jobs is the
 * interface for looking at anything else. No second canvas, no flow editor, no second store, and
 * nothing to adopt from a 55k-star archived platform to get it.
 *
 * It is also what kb:agent-orchestration has said since it was written: A TASK IS A TRIPLE, and
 * the graph is the config. jobs.json was the exception nobody had converted.
 *
 * DIRECTION OF TRUTH, deliberately conservative for now. jobs.json REMAINS the source and this
 * generates a graph view of it, checked by an align gate. The doctrine says the graph should be
 * the source and jobs.json the generated artifact — but the offline sweep reads jobs.json on every
 * run, and inverting that before the graph view has been looked at once would risk the sweep to
 * make a point. Flipping later is a small change; a broken sweep is not.
 *
 * SETS, NOT A SECOND GROUPING MECHANISM. Jobs group by TIER into skos:Collection, using the same
 * primitive as everything else — kb:entity-sets is explicit that building a parallel grouping is
 * the duplication scripts/offline/shared-deps.ts exists to catch, and names job grouping as one of
 * its three consumers.
 *
 * Usage: npx tsx scripts/jobs-graph.ts [--check]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname ?? '.', '..');
const JOBS = join(ROOT, 'scripts', 'offline', 'jobs.json');
const OUT = join(ROOT, 'static', 'reckons-jobs.ttl');
const CHECK = process.argv.includes('--check');

interface Job { name: string; tier: string; enabled: boolean; cmd: string; desc: string; blocking?: boolean }

const esc = (s: string): string => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ').trim();
const slug = (s: string): string => s.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '');

function build(): string {
  const raw = JSON.parse(readFileSync(JOBS, 'utf8')) as Job[] | { jobs: Job[] };
  const jobs = (Array.isArray(raw) ? raw : raw.jobs).slice().sort((a, b) => a.name.localeCompare(b.name));

  const L: string[] = [
    '@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .',
    '@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .',
    '@prefix skos:   <http://www.w3.org/2004/02/skos/core#> .',
    '@prefix ktype:  <urn:kbase:type/> .',
    '@prefix kpred:  <urn:kbase:predicate/> .',
    '@prefix job:    <urn:reckons:job/> .',
    '@prefix jobset: <urn:reckons:jobset/> .',
    '',
    '## ---------------------------------------------------------------------------',
    '## GENERATED by scripts/jobs-graph.ts from scripts/offline/jobs.json.',
    '## Do not hand-edit: run `npm run jobs:graph`. The align gate checks the two agree.',
    '##',
    '## Why this file exists: kb:agent-orchestration says a task is a triple and the',
    '## graph is the config, and jobs.json was the exception nobody had converted. As',
    '## entities the jobs render in the graph UI that already exists, which is the',
    '## whole of the "we need a GUI for offline tasks" problem.',
    '## ---------------------------------------------------------------------------',
    '',
    '<urn:reckons:kb> <urn:reckons:meta/kbStableId> "a1b2c3d4-e5f6-4a0d-b00d-000000000013" .',
    '',
  ];

  for (const j of jobs) {
    const iri = `job:${slug(j.name)}`;
    L.push(`${iri} rdf:type          ktype:OfflineJob ;`);
    L.push(`    rdfs:label          "${esc(j.name)}" ;`);
    L.push(`    skos:prefLabel      "${esc(j.name)}" ;`);
    if (j.desc) L.push(`    skos:definition     "${esc(j.desc)}" ;`);
    L.push(`    kpred:job-tier      "${esc(j.tier)}" ;`);
    L.push(`    kpred:command       "${esc(j.cmd)}" ;`);
    // Enabled and blocking are the two facts that change what a sweep DOES, so they are stated
    // rather than left implicit in the absence of a flag.
    L.push(`    kpred:job-enabled   "${j.enabled ? 'true' : 'false'}" ;`);
    L.push(`    kpred:job-blocking  "${j.blocking ? 'true' : 'false'}" .`);
    L.push('');
  }

  // ── Tiers as sets. The same primitive entity grouping uses; not a parallel mechanism.
  const tiers = [...new Set(jobs.map((j) => j.tier))].sort();
  const TIER_NOTE: Record<string, string> = {
    script: 'Deterministic, zero tokens, no model. Right by construction and runs in CI. The work-tiering ladder says to grow this tier in preference to the others, and it is the larger one.',
    agent: 'A local model inside a scripted harness — ground, prompt, validate, emit-proposal. Output is a PROPOSAL a human gates, never a write, because being wrong here has to be cheap.',
  };
  for (const tier of tiers) {
    const members = jobs.filter((j) => j.tier === tier);
    L.push(`jobset:${slug(tier)} rdf:type      skos:Collection ;`);
    L.push(`    skos:prefLabel      "${esc(tier)} tier" ;`);
    L.push(`    skos:definition     "${esc(TIER_NOTE[tier] ?? `Jobs at the ${tier} tier.`)}" ;`);
    L.push(`    skos:member         ${members.map((m) => `job:${slug(m.name)}`).join(', ')} .`);
    L.push('');
  }

  L.push('jobset:all rdf:type          skos:Collection ;');
  L.push('    skos:prefLabel      "Offline jobs" ;');
  L.push(`    skos:definition     "Every job the offline sweep can run — ${jobs.length} of them, ${jobs.filter((j) => j.tier === 'script').length} needing no model at all." ;`);
  L.push(`    skos:member         ${tiers.map((t) => `jobset:${slug(t)}`).join(', ')} .`);
  L.push('');

  return L.join('\n');
}

function main(): void {
  const ttl = build();
  if (CHECK) {
    const existing = (() => { try { return readFileSync(OUT, 'utf8'); } catch { return ''; } })();
    if (existing !== ttl) {
      console.error('✗ static/reckons-jobs.ttl is stale. Run: npm run jobs:graph');
      process.exit(1);
    }
    console.log('✓ jobs graph matches scripts/offline/jobs.json');
    return;
  }
  writeFileSync(OUT, ttl, 'utf8');
  const n = (ttl.match(/rdf:type          ktype:OfflineJob/g) ?? []).length;
  console.log(`✓ ${n} job(s) written to static/reckons-jobs.ttl, grouped into tier sets`);
}

main();
