#!/usr/bin/env bash
# Set up the Reckons workspace with symlinks to TTL documentation KBs.
#
# This workspace serves two purposes:
#   1. MCP server reads from it (Claude Code, VS Code, etc.)
#   2. Reckons.AI app syncs with it (via Settings > Workspace folder)
#
# KB discovery is by folder name + {folder}.ttl (legacy fallback: kb.ttl) — no meta.json needed.
#
# Run after cloning or when symlinks break:
#   bash scripts/setup-reckons-workspace.sh

set -euo pipefail
cd "$(dirname "$0")/.."

WORKSPACE="reckons-workspace"
KBS="$WORKSPACE/kbs"

echo "Setting up Reckons workspace..."

mkdir -p "$KBS"/{production,roadmap,features,docs,quickstart,codebase,architecture}

# Clean up legacy meta.json files (no longer needed — discovery uses {folder}.ttl)
find "$KBS" -name meta.json -delete 2>/dev/null || true

# Clean up stale legacy kb.ttl symlinks (superseded by {folder}.ttl below)
find "$KBS" -name kb.ttl -delete 2>/dev/null || true

# Symlink TTL files (3 levels up from kbs/{name}/ to reach static/)
ln -sf ../../../static/reckons-production.ttl "$KBS/production/production.ttl"
ln -sf ../../../static/reckons-roadmap.ttl    "$KBS/roadmap/roadmap.ttl"
ln -sf ../../../static/docs-features.ttl      "$KBS/features/features.ttl"
ln -sf ../../../static/starter-quickstart.ttl "$KBS/quickstart/quickstart.ttl"
ln -sf ../../../static/reckons-codebase.ttl   "$KBS/codebase/codebase.ttl"
ln -sf ../../../static/docs-architecture.ttl  "$KBS/architecture/architecture.ttl"

# Docs KB: merge all sub-graphs into one file, then symlink
cat static/starter-guide.ttl \
    static/docs-triples-rdf.ttl \
    static/docs-llm.ttl \
    static/docs-use-cases.ttl \
    static/docs-integrations-tech.ttl \
    static/docs-tips-security.ttl \
    static/docs-timeline-ecosystem.ttl \
    > static/docs-all.ttl
ln -sf ../../../static/docs-all.ttl "$KBS/docs/docs.ttl"

echo "Workspace ready: $WORKSPACE/ (7 KBs, symlinked to static/*.ttl)"

# ── mcp-workspace: the graphs Claude Code's `reckons` MCP server reads ─────────
#
# .mcp.json (committed) points the server at mcp-workspace/, but that directory is
# GITIGNORED — so without this block a fresh clone gets a configured MCP server with
# nothing to read. It was also hand-made once and then drifted: on 2026-07-18 the
# `architecture` and `testing` folders existed but were EMPTY and `codebase` was absent,
# so the server silently served 3 graphs while CLAUDE.md described 6. Building it from a
# script instead of by hand is what stops that recurring.

MCP_WS="mcp-workspace"
MCP_KBS="$MCP_WS/kbs"

echo "Setting up MCP workspace..."

find "$MCP_KBS" -name meta.json -delete 2>/dev/null || true
find "$MCP_KBS" -name kb.ttl -delete 2>/dev/null || true

# LINK EVERY GRAPH, NOT A HAND-PICKED SIX (fixed 2026-08-26).
#
# This script used to link exactly six graphs. That IS the F104 coverage bug —
# "the MCP server sees 6 of 23 graphs ... INVISIBLE to kb_search: reckons-shipped.ttl
# (the SHIPPED, production-status features — so a search for completed work can
# return nothing and invite a rebuild)". The working workspace was repaired by hand
# and reached 23 graphs; this script was never updated, so every fresh clone
# silently recreated the bug and F104's fix depended on one machine's local state.
#
# Derived from static/*.ttl rather than enumerated, so a NEW graph is covered the
# day it is added instead of the day somebody remembers this file. graph-lint's
# mcp-invisible check is the backstop, and it now has to find nothing.
declare -A MCP_EXCLUDE=(
  # Generated by the docs concatenation above; linked separately as docs-hub so the
  # merged view exists exactly once rather than also appearing per-fragment.
  [docs-all.ttl]=1
  # Deployment/site status, not knowledge an agent should search for answers in.
  [website.ttl]=1
  [website-status.ttl]=1
  # Path inventory regenerated from git; enormous, and reckons-codebase.ttl already
  # carries the module structure an agent actually wants.
  [reckons-code-files.ttl]=1
)

# Names that read better than their filename, kept stable so existing kb= arguments
# and any saved queries keep resolving.
declare -A MCP_RENAME=(
  [reckons-production.ttl]=production
  [reckons-roadmap.ttl]=roadmap
  [reckons-codebase.ttl]=codebase
  [reckons-competitive.ttl]=competitive
  [reckons-safety-log.ttl]=safety-log
  [reckons-shipped.ttl]=shipped
  [docs-architecture.ttl]=architecture
  [docs-features.ttl]=features
  [docs-testing.ttl]=testing
  [docs-coding-workflow.ttl]=coding-workflow
  [docs-integrations-tech.ttl]=integrations-tech
  [docs-llm.ttl]=llm
  [docs-timeline-ecosystem.ttl]=timeline-ecosystem
  [docs-tips-security.ttl]=tips-security
  [docs-triples-rdf.ttl]=triples-rdf
  [docs-use-cases.ttl]=use-cases
)

linked=0
for src in static/*.ttl; do
  base="$(basename "$src")"
  [ -n "${MCP_EXCLUDE[$base]:-}" ] && continue
  name="${MCP_RENAME[$base]:-${base%.ttl}}"
  mkdir -p "$MCP_KBS/$name"
  ln -sf "../../../static/$base" "$MCP_KBS/$name/$name.ttl"
  linked=$((linked + 1))
done

# The merged docs view, under the name the existing workspace already uses.
mkdir -p "$MCP_KBS/docs-hub"
ln -sf ../../../static/docs-all.ttl "$MCP_KBS/docs-hub/docs-hub.ttl"
linked=$((linked + 1))

# Fail loudly if a link is dangling — a silently-empty graph is how the drift above
# went unnoticed for weeks.
missing=0
for f in "$MCP_KBS"/*/*.ttl; do
  [ -e "$f" ] || { echo "  BROKEN LINK: $f"; missing=1; }
done
[ "$missing" -eq 0 ] || { echo "MCP workspace has dangling symlinks — fix static/*.ttl paths above."; exit 1; }

echo "MCP workspace ready: $MCP_WS/ ($linked graphs) — restart Claude Code to pick up .mcp.json"

# ── Personal example graphs ──────────────────────────────────────────────────
#
# COPIED, NEVER SYMLINKED, and the distinction is the whole point. Everything
# above is the PROJECT describing itself, so a symlink is right: edit the graph,
# edit the repo. These are starting points for YOUR data, and reckons-workspace/
# kbs/** is gitignored entirely — so a symlink here would make your first edit to
# a personal notes graph a modification of a tracked file, which is exactly the
# confusion the separation exists to prevent.
#
# Never overwrites. If a graph of that name already exists it is yours now, and
# a setup script has no business touching it.

echo "Seeding personal example graphs..."
seeded=0
skipped=0
for src in static/examples/*.ttl; do
  name="$(basename "$src" .ttl)"
  # README.ttl documents the boundary for a reader of the repo; it is not a graph
  # anybody wants in their workspace graph list.
  [ "$name" = "README" ] && continue
  dest_dir="$KBS/$name"
  dest="$dest_dir/$name.ttl"
  if [ -e "$dest" ]; then
    skipped=$((skipped + 1))
    continue
  fi
  mkdir -p "$dest_dir"
  cp "$src" "$dest"
  seeded=$((seeded + 1))
  echo "  seeded $name"
done
if [ "$skipped" -gt 0 ]; then
  echo "  ($skipped example(s) already present — left alone, they are yours now)"
fi
echo "Personal examples: $seeded seeded, $skipped kept."
